name: expensetracker
description: "Expense Tracker Android app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/geist/Geist-Black.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
